version: "3"
services:
  nginx:
    image: nginx:1.13.6
    container_name: nginx
    ports:
      # 将主机的 80 端口映射到容器的 80 端口
      - 80:80
      # ssl 默认是443端口，因此需要将443端口映射到宿主机上
      - 443:443
    links:
      - php    
    volumes:
      # 同 php 一起共享 /data/www 目录
      - /data/www:/data/www
      # nginx 配置文件
      - $PWD/config/nginx:/etc/nginx/conf.d:ro
      # nginx 日志
      - /data/log/www/:/var/log/nginx:rw
    restart: always

  php:
    # Dockerfile 构建
    build: $PWD/build/php
    container_name: php
    volumes:
      #  网站根目录
      - /data/www:/data/www
      # php 配置文件
      - $PWD/config/php/conf.d:/usr/local/etc/php/conf.d:ro
      - /tmp:/tmp:rw
    links:
      - mysql:db
      - redis
    restart: always

  redis:
    image: redis:4.0.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      # redis 配置文件
      - $PWD/config/redis:/etc/redis:ro
      # redis 持久化数据存储
      - /data/redis:/data/redis
    # 以配置文件启动 redis
    command: redis-server /etc/redis/redis.conf
    restart: always

  mysql:
    image: mysql:5.7.20
    container_name: mysql
    # 配置环境变量
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      # mysql 配置文件
      - $PWD/config/mysql/conf.d:/etc/mysql/conf.d:rw
      # 下面的目录配置文件会覆盖上面的
      - $PWD/config/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d:rw
      # mysql 数据库
      - /data/mysql:/var/lib/mysql:rw
      # mysql 日志
      - /data/log/mysql:/var/log/mysql:rw
      - /tmp:/tmp:rw
    restart: always
